version: '3'
services:
  #授权服务
  boom_admin:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/boom_admin:latest
    container_name: boom_admin
    restart: always
    ports:
      - 8601:8601
    networks:
      - boom
    environment:
      - COMPOSE_PROJECT_NAME=boom_admin
    volumes:
      - ../log/:/logs/
      - ../config/boom_admin/:/config/
networks:
  boom:
    external: true