version: '3.1'
services:
  redis:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass boom2018 --appendonly yes # 启动redis服务并添加密码为：boom2018,并开启redis持久化配置
    volumes:
      - ../data/redis_data:/data
    networks:
      - boom
      
networks:
  boom:
    external: true
