version: '3.1'
services:
  sentinel:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/sentinel
    restart: always
    container_name: sentinel
    ports:
      - 8070:8070
    networks:
      - boom

networks:
  boom:
    external: true
