version: '3'
services:
  #授权服务
  vue_boom_web:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/vue_boom_web:latest
    container_name: vue_boom_web
    restart: always
    ports:
      - 9527:80
    networks:
      - boom
    env_file:
      - ../config/vue_boom_web.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_boom_web
networks:
  boom:
    external: true
