version: '3'
services:
  #授权服务
  vue_boom_admin:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/vue_boom_admin:latest
    container_name: vue_boom_admin
    restart: always
    ports:
      - 9528:80
    networks:
      - boom
    env_file:
      - ../config/vue_boom_admin.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_boom_admin

networks:
  boom:
    external: true
