version: '3.1'
services:
  zipkin:
    image: registry.cn-shenzhen.aliyuncs.com/boomblog/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=zipkin
      - MYSQL_USER=root
      - MYSQL_PASS=boom2018
      - MYSQL_HOST=mysql
      - MYSQL_TCP_PORT=3306
    ports:
      - 9411:9411
    networks:
      - boom

networks:
  boom:
    external: true
