###############################################################################
# Nacos分支的配置文件存储在nacos中【包括数据库配置、Redis配置、RabbitMQ等 ..】         #
##############################################################################
spring:
  profiles:
    #启动dev环境的配置文件
    active: dev