###############################################################################
# Nacos分支的配置文件存储在nacos中【包括数据库配置、Redis配置、RabbitMQ等 ..】         #
##############################################################################
spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300